### ISSUE TITLE
Colorado Basin River Forecast Center data

### ISSUE THREAD

**Issue by davetapley** [DOI-USGS/dataretrieval-python#102]
Admittedly not USGS, but is ⬇️ in scope for this project?
https://www.cbrfc.noaa.gov

I'm happy to help with PRs if it is.

**Comment by lstanish-usgs** [comment]
Hey @davetapley might I suggest a quick meeting to get a better idea about what you are thinking? Feel free to email comptools@usgs.gov if you want to set something up. Thanks!
