### ISSUE TITLE
get_gwlevels: Value Error using example

### ISSUE THREAD

**Issue by jnmitchell-USGS** [DOI-USGS/dataretrieval-python#108]
The "get_gwlevels" function returns the below error for all attempted site numbers, even when running the example code ("dataretrieval-python/demos/hydroshare/USGS_dataretrieval_GroundwaterLevels_Examples.ipynb") verbatim:

*ValueError: unconverted data remains when parsing with format "%Y-%m-%d %H:%M": " +0000", at position 0. You might want to try: - passing* `format` if your strings have a consistent format; - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format; - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

**Comment by jnmitchell-USGS** [comment]
I solved this by setting "datetime_index" to False.

**Comment by elbeejay** [comment]
@jnmitchell-USGS I think this is related to #93 and #104 - I'd check your version of `pandas` and make sure it is <2 or alternatively check your version of `dataretrieval` and make sure it incorporates changes from #104.
