### ISSUE TITLE
create ChangeLog

### ISSUE THREAD

**Issue by lstanish-usgs** [DOI-USGS/dataretrieval-python#126]
The auto-generated release notes created by GitHub are OK, but they rely on users accurately describing the work involved in an issue or pull request. They also aren't available outside of GitHub. 
It would be great to have a ChangeLog document with a bulleted list (or similar) of the key revisions made between release versions. Here are some examples:

- R dataRetrieval has a [NEWS](https://github.com/DOI-USGS/dataRetrieval/blob/main/NEWS) page
- This is from [nhdPlusTools](https://github.com/DOI-USGS/nhdplusTools/blob/main/NEWS.md)
- This is a [random one](https://github.com/DOI-USGS/knoten/blob/main/CHANGELOG.md) I found in another python repo which claims to adhere to some best practices.

**Comment by thodson-usgs** [comment]
With all due respect to their developers (who are two of the best in USGS), USGS packages aren't the best exemplars.
Reviewing a few community projects has reconfirmed my recollection that changelog.md is deprecated; for example: https://github.com/pymc-devs/pymc/blob/main/RELEASE-NOTES.md.
Going forward, I think the best practice is to revise the auto-generated release notes.
