### ISSUE TITLE
Data downloading issue with a specific gauging station

### ISSUE THREAD

**Issue by pppxiyu** [DOI-USGS/dataretrieval-python#129]
I tried to download iv data from about 1k gauges using a for loop. All of the iterations was successful except for gauge '05427530'. 
Error: "KeyError: '72255_y'".

Codes:
```
nwis.get_record(sites='05427530', service='iv', start='2018-12-24', end='2023-12-24')
```

**Comment by thodson-usgs** [comment]
Interesting. I started looking into it but haven't gotten to the bottom of it yet. Gauges are operated by Water Science Centers that sometimes follow different conventions, which might be breaking something in `dataretrieval`. We already do opinionated things to compensate for such problems and I mainly want to ensure that whatever we introduce does more good than harm.

**Comment by thodson-usgs** [comment]
@pppxiyu,
I think I've resolved the issue but, I'd like to test this on your loop.
Would install the patch in a new or existing environment and rerun your code?
```bash
pip install git+https://github.com/DOI-USGS/dataretrieval-python@129-data-downloading-issue-with-a-specific-gauging-station
```

**Comment by thodson-usgs** [comment]
Nope, this breaks multisite retrievals. Working on the fix

**Comment by thodson-usgs** [comment]
@pppxiyu, okay test it now if you would. As before:
```bash
pip install git+https://github.com/DOI-USGS/dataretrieval-python@129-data-downloading-issue-with-a-specific-gauging-station
```
and if you didn't create a new environment, you'll want to `pip remove dataretrieval` when you're done, and reinstall from pypi/conda.
