### ISSUE TITLE
Update code coverage link to correct instance of coveralls

### ISSUE THREAD

**Issue by whatnick** [DOI-USGS/dataretrieval-python#139]
The README for this repository includes link to code coverage from coveralls, but I can't spot the relevant CI pipeline for running coverage and uploading the results. The link also returns empty results. Perhaps setting up a properly linked Coveralls instance will be helpful pointing to - https://coveralls.io/github/DOI-USGS/data_retrieval?branch=master

**Comment by thodson-usgs** [comment]
Good suggestion, but I don't think I have permission to use coveralls with this GitHub org.
