### ISSUE TITLE
Unable to use dataretrieval package after using it succesfully for awhile

### ISSUE THREAD

**Issue by andrewrfrench** [DOI-USGS/dataretrieval-python#144]
I used datatretrieval package for a week or two in Spyder in a conda environment, then it stopped working completely. 

Traceback (most recent call last):

  File ~/miniconda3/envs/usgs/lib/python3.11/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Documents/DataAnalysis/USGS1/multi_site.py:2
    import dataretrieval.nwis as nwis

  File ~/Documents/DataAnalysis/USGS1/dataretrieval.py:6
    import dataretrieval.nwis as nwis

ModuleNotFoundError: No module named 'dataretrieval.nwis'; 'dataretrieval' is not a package

I tried many things, including creating several environments, reinstalling, etc... So far no go. I am able to load the package in the python in the terminal without an issue, but not in the Spyder IDE, which leads me to believe it has something to do with Spyder, or the py3compat.py file.

**Comment by thodson-usgs** [comment]
Seems like an environment issue. I don't use Spyder, but I'd start by dumping out a list of all the packages in your environment.
