### ISSUE TITLE
Service = ‘dv’ returning shorter record than available from station webpage

### ISSUE THREAD

**Issue by JoeShmoJo** [DOI-USGS/dataretrieval-python#146]
Downloading 00060 flow records using service ‘iv’ and ‘dv’ result in equal record lengths, but a longer daily record is available on the USGS station webpage. How can I access the longer daily record using dataretrieval?

**Comment by thodson-usgs** [comment]
Can you provide a code example?

**Comment by JoeShmoJo** [comment]
I cannot reproduce. This appears to be an error on my part. Apologies. Please delete.
