### ISSUE TITLE
rename `master` to `main` branch

### ISSUE THREAD

**Issue by ehinman** [DOI-USGS/dataretrieval-python#155]
We should keep up with the times here. However, need to consider how this will affect contributors.

**Comment by thodson-usgs** [comment]
Go for it. It could break certain use patterns, but no way around it.

**Comment by ehinman** [comment]
## NOTICE TO DEVELOPERS:
In line with this issue, we are changing the default branch name from `master` to `main`. This will affect your forks of the `dataretrieval-python` repository. Please read below for instructions on updating your forks and local branches.
@pkdash @thodson-usgs @kjdoore @jlarsen-usgs @rckwzrd @lstanish-usgs @ldecicco-USGS @mnfienen @edsaac @davetapley @elbeejay @douglasdennis @cjbas22 @jzemmels @jsta @jbousquin @elmerehbi @sblack-usu

### Changing default branches on forks and local clones
First, update your local git configuration so that new repositories created locally will have the correct default branch: git config --global init.defaultBranch main.

Now, for any forks, do the following:

Go to <your fork> -> Settings -> Branches and edit the default branch from master to main.
Update the settings for your local clone of this fork to match this change.

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
