### ISSUE TITLE
Index without Timezone info throws error

### ISSUE THREAD

**Issue by msweier** [DOI-USGS/dataretrieval-python#17]
I just downloaded this and was testing and got an error retrieving instantaneous values at site 05046000. 
![image](https://user-images.githubusercontent.com/9432394/98011120-17305500-1dbd-11eb-89df-471e22790d36.png)

Seems like the format_response function needs some sort of catch in case a column named 'datetime' exists, but it does not have any tzinfo associated with it. I put it in a try block and return the dataframe if it fails.

![image](https://user-images.githubusercontent.com/9432394/98011496-89a13500-1dbd-11eb-911f-789b7b2a2f2e.png)

Maybe a more official fix can be done. Thanks!

**Comment by elbeejay** [comment]
@msweier I know it has been a long time since you submitted this issue, but do you happen to recall what the actually input was that resulted in that error? Several changes to the code have been made since this issue was opened, and right now the code below works without any errors.

```
>>> import dataretrieval.nwis as nwis
>>> df = nwis.get_record(sites='05046000', service='iv', start='2022-12-20', end='2022-12-21')
```

**Comment by msweier** [comment]
Hi @elbeejay, I can't recall for certain. I do remember if a timeseries had multiple stage values from different sensors for the same time value (e.g. radar, bubbler) that would give me issues, but I don't if it was causing this one.

**Comment by elbeejay** [comment]
Thanks for following up @msweier - I'll keep an eye out for this as we continue development and create additional tests and examples of functionality.
