### ISSUE TITLE
Stat Service

### ISSUE THREAD

**Issue by djdean1979** [DOI-USGS/dataretrieval-python#31]
Any prediction when the "stat" service will be available? I am getting an error trying to pull annual flow stats from the web indicating that the "stat" service is not yet active

**Comment by thodson-usgs** [comment]
Can provide code to replicate the error? I just tried the stat service and didn't have any issue.

**Comment by djdean1979** [comment]
import dataretrieval.nwis as nwis
site='01491000'
# download mean annual flow from a single site
df = nwis.get_record(sites=site, service='stat', start='1970-10-01', end='2000-09-30')
df.head()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-152cd74dfae6> in <module>
      2 site='01491000'
      3 # download mean annual flow from a single site
----> 4 df = nwis.get_record(sites='01491000', service='stat', start='1970-10-01', end='2000-09-30')
      5 df.head()

C:\ProgramData\Anaconda3\lib\site-packages\dataretrieval\nwis.py in get_record(sites, start, end, state, service, *args, **kwargs)
    618 
    619     else:
--> 620         raise TypeError('{} service not yet implemented'.format(service))
    621 
    622 

TypeError: stat service not yet implemented

**Comment by djdean1979** [comment]
I get the same error when I simply enter the year, without the month and day.

**Comment by thodson-usgs** [comment]
I see the problem now. I haven't implemented the stat service within get_record, but you can still access the stat service via nwis.get_stat().
I'll have to check why it was never added to get_record(). If I don't see an issue, I'll go ahead and add it.
