### ISSUE TITLE
Packaging for conda-forge

### ISSUE THREAD

**Issue by jsta** [DOI-USGS/dataretrieval-python#44]
I'm interested in getting this hosted on [conda-forge](https://conda-forge.org/). Any concerns or volunteers to be a "maintainer"?

https://github.com/conda-forge/staged-recipes/pull/18526

**Comment by thodson-usgs** [comment]
@jsta, I see you closed this, but we can reopen if you like.

I'm not opposed to adding "maintainers" but allow me to think it over, then we can schedule a time to chat.

Regarding conda-forge, yes! How should we proceed? https://github.com/conda-forge/automerge-action ?

**Comment by elbeejay** [comment]
@jsta it'd be great if @thodson-usgs and I could be added as maintainers for the conda-forge recipe - do you know if we'd re-open the original recipe issue to do this or if we have to create a new one? Thanks!

**Comment by jsta** [comment]
There's a bot command that will open a PR to add maintainers. I'll merge PR's if you open them.
https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username

**Comment by jsta** [comment]
See https://github.com/conda-forge/mastodon.py-feedstock/issues/15
