### ISSUE TITLE
warning in Python Equivalents to R Vignettes doc

### ISSUE THREAD

**Issue by lstanish-usgs** [DOI-USGS/dataretrieval-python#88]
I'm seeing an odd warning on this documentation page, is this just on my end?

https://doi-usgs.github.io/dataretrieval-python/examples/rvignettes.html#Embedded-Metadata
![image](https://user-images.githubusercontent.com/89864109/219702621-91340cce-6705-4bfb-a94b-c592d543ddc4.png)

Thanks.

**Comment by elbeejay** [comment]
Warning is correct as shown, the requested data does not have complete datetime information for 189 of the entries so the user is informed of this and given a suggestion to turn off data frame indexing by datetime.

**Comment by elbeejay** [comment]
Closing unless there's something else to discuss here...
