### ISSUE TITLE
Possible bug in json parsing

### ISSUE THREAD

**Issue by elbeejay** [DOI-USGS/dataretrieval-python#90]
Querying some instantaneous data with `get_iv`:

```
df, md = nwis.get_iv(
    sites='05370000', start='2022-01-01', end='2022-02-22',
    parameterCd='00065')
```

the resulting data frame:

```
df.head()
                           00065_2 00065_2_cd   site_no   00065 00065_cd
datetime                                                                
2022-01-01 06:00:00+00:00     12.2          A  05370000  912.24        P
2022-01-01 06:15:00+00:00     12.2          A  05370000  912.24        P
2022-01-01 06:30:00+00:00     12.2          A  05370000  912.24        P
2022-01-01 06:45:00+00:00     12.2          A  05370000  912.24        P
2022-01-01 07:00:00+00:00     12.2          A  05370000  912.24        P
```

The column names for values are `00065_2` and `00065`. I expected them to be `237348_00065` and `317599_00065` per [the RDB return](https://waterservices.usgs.gov/nwis/iv/?sites=05370000&parameterCd=00065&startDT=2023-02-16T09:27:14.109-06:00&endDT=2023-02-23T09:27:14.109-06:00&siteStatus=all&format=rdb). Although that made me wonder if we should be expecting to match the RDB return?

Some further investigation was done by examining the JSON response object:

```
response = nwis.query_waterservices('iv', format='json',
                                    startDT='2022-02-14',
                                    endDT='2022-02-22',
                                    sites='05370000',
                                    parameterCd="00065")
```

In the [JSON](https://waterservices.usgs.gov/nwis/iv/?sites=05370000&parameterCd=00065&startDT=2023-02-16T09:27:14.109-06:00&endDT=2023-02-23T09:27:14.109-06:00&siteStatus=all&format=json) the integers preceding the parameter code are "methodID" values.

When we parse the JSON in `_read_json`, we differentiate between these multiple methods for a single parameter value by looking at the "methodDescription" field ([line 1077](https://github.com/DOI-USGS/dataretrieval-python/blob/cfe78ae0efcebe2426cfa1b5ebb346119648d55d/dataretrieval/nwis.py#L1077)) rather than the "methodID" field.

Was this implementation intentional? Or can we switch to looking at the "methodID" field, and then use that as a *prefix* to the parameterCd when setting the column names. This would result in a return that matches the column names in the RDB file. 

Again, I'm not stuck on matching the RDB file, and the current implementation seems to work, just checking if this is a bug or behavior as intended.

**Comment by jkreft-usgs** [comment]
the other thing is that the "methodID" in the JSON is basically a misnomer, it has nothing to do with method.  Instead that number is the `TS_ID`, which is laid out at the top of the RDB file.

```
# TS_ID - An internal number representing a time series.
#
# Data provided for site 05370000
#    TS_ID       Parameter Description
#    237348      00065     Gage height, feet, [(2)]
#    317599      00065     Gage height, feet
#
```

**Comment by elbeejay** [comment]
To be clear @thodson-usgs, we currently parse the "methodDescription" not the "methodID". Is that intentional? Your comment above makes it sound like we should be parsing the "methodID"?

**Comment by thodson-usgs** [comment]
My mistake. "methodDescription" was chosen intentionally. Based on the data I was pulling, it seemed to be the best option, with the caveat that usage can be somewhat inconsistent across projects.

**Comment by elbeejay** [comment]
Well it doesn't seem like this is a bug with `dataretrieval`, the "fix", if implemented, would be to update the JSON file delivered by the API to include the TS_ID field - only then would we have to consider changing anything here.
