### ISSUE TITLE
Pandas 2.x.x breaking change

### ISSUE THREAD

**Issue by elbeejay** [DOI-USGS/dataretrieval-python#93]
The upgrade in `pandas` to v2.0.0 on April 3 has actually broken `dataretrieval` - we just haven't tried to run the CI pipeline yet. Could pin pandas to be `<2` in `requirements.txt` for a quick fix while we work to resolve the root issues... thoughts @thodson-usgs?

**Comment by thodson-usgs** [comment]
Will get a sense of scope this afternoon. We can do that if the fix isn't quick.

**Comment by thodson-usgs** [comment]
@elbeejay,
This will break old versions, eh? Should've pinned pandas all along.
Go ahead and pin `=1`, which should match 1.X.X.

I've started a fix, which I'll pin at `pandas=2`

**Comment by elbeejay** [comment]
`pandas` pinned in https://github.com/DOI-USGS/dataretrieval-python/commit/7326dfdcba32fb18d59b5fad24fd225b40348058

Tagged release: https://github.com/DOI-USGS/dataretrieval-python/releases/tag/v1.0.4

**Comment by thodson-usgs** [comment]
@elbeejay, I started this put was pulled in other directions. I forget the issue, but this would be good to fix before we release our next version.
