### ISSUE TITLE
Surpress UserWarning:  GDAL not installed.

### ISSUE THREAD

**Issue by davetapley** [DOI-USGS/dataretrieval-python#99]
I know it's not _specific_ to this repo, but has anyone found a way to surpress this:
https://github.com/DOI-USGS/dataretrieval-python/blob/7326dfdcba32fb18d59b5fad24fd225b40348058/dataretrieval/nadp.py#L44

I tried [this](https://stackoverflow.com/a/53706908/21115) but it doesn't work 😑 

```py
filterwarnings(
    action='ignore',
    category=UserWarning,
    module=r'.*nadp'
)
```

**Comment by davetapley** [comment]
This works 🤷🏻 

```py
from warnings import catch_warnings, simplefilter

with catch_warnings():
    simplefilter("ignore")
    import dataretrieval.nwis as nwis
```

**Comment by elbeejay** [comment]
@davetapley wanted to let you know that the latest release removed that warning, see #96. Another user had a similar issue to yours (#94) and we opted to simply remove `gdal` as an import.
